baseurl = "https://example.com"
title = ""
author = "@JeffProd"
copyright = "Copyright © 2008–2018, @JeffProd"
canonifyurls = true
paginate = 3
banner = "default_sharing_image"

theme = "jeffprod"

[taxonomies]
    tag = "tags"
    issue = "issues"
    archive = "archives"
    category = "categories"
